# Generated by Django 4.1.3 on 2022-11-26 10:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_post_comments_remove_post_tags_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[330, 85], upload_to='category'),
        ),
    ]
