# Generated by Django 4.1.3 on 2022-12-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_about_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(default='11', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='11', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='phone_number',
            field=models.CharField(default='11', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='11', max_length=70),
            preserve_default=False,
        ),
    ]
