# Generated by Django 4.1.3 on 2022-12-10 10:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_user_gender_user_phone_number_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': "Ma'lumot", 'verbose_name_plural': "Ma'lumot"},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Postlar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, 250], upload_to='users'),
        ),
    ]
