# Generated by Django 4.1.3 on 2022-12-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Mavjud emas', max_length=25, null=True),
        ),
    ]
